version: "3.4"

services:
  sn-masterdata01:
    container_name: sn-masterdata01
    image: sn-masterdata01
    environment:
      - PORT=5000
    ports:
      - 5000:5000
    build:
      context: .
      dockerfile: Dockerfile